### PR TITLE
Remove garbage "function:" items from node data

### PR DESCRIPTION
**Pull request by alxndr42**

### CODE REVIEW

**Comment by rubo77** [comment]
When do those elements starting with"function:" occur? And why do they have to be removed?

**Comment by alxndr42** [comment]
They're in the JSON that's coming from Alfred and end up in our nodes.json. Since Alfred is apparently being dropped soon(tm), I didn't investigate further.

The garbage is causing problems with the [node_hierarchy](https://github.com/FreiFunkMuenster/node_hierarchy) script we want to use for the domain split.

**Comment by rubo77** [comment]
Your suggested change seems ok, although I cannot test it, in none of our communities nord, kiel and lübeck, we have suche a key, containing "function:"

can you provide an example?

**Comment by alxndr42** [comment]
Here is one example:

```
"mesh": {
  "function: 0x9cd7f08": true,
  "bat0": {
    "interfaces": {
      "tunnel": [
        "02:1c:71:4d:0d:35"
      ],
      "function: 0x9cd7f08": true
    },
    "function: 0x9cd7f08": true
  }
},
```

**Comment by rubo77** [comment]
And what Kind of node does create this?

**Comment by alxndr42** [comment]
@rubo77 Didn't check.

@kantorkel hast Du auch den Backend-Hut auf, oder macht das mehr @baldo? Auf diesem Branch sind ein paar weitere Commits, die noch nicht auf srv02 laufen. Würde ich gerne alles nächsten Freitag auf srv02 bringen, damit das oben erwähnte Skript mal laufen kann.

**Pull request closed without merging**
